### PR TITLE
qSort -> std::sort

### PR DESCRIPTION
**Pull request by ChungZH**
测试过了测试过了测试过了

又少了一个 warn

### CODE REVIEW

**Comment by ChungZH** [comment]
@rekols 鸽鸽？

**Comment by reionwong** [comment]
thanks

**Comment by milohr** [comment]
This change will make the app crash on folders with many files. The optimal solution was introduced to mauikit filebrowsing here:
https://invent.kde.org/maui/mauikit-filebrowsing/-/blob/master/src/code/fmlist.cpp#L236

**Comment by itsvic-dev** [comment]
> This change will make the app crash on folders with many files. The optimal solution was introduced to mauikit filebrowsing here:
> https://invent.kde.org/maui/mauikit-filebrowsing/-/blob/master/src/code/fmlist.cpp#L236
> 

could you tell us why it will crash?

**Comment by milohr** [comment]
Im not sure why, it has to do with missused of the second parameter on the std sort predicate function.

You could test it yourself on a direcrory like /bin

Also here the right key to sort the folders first was removed and instead is using the captured key value which is the order value.

What the fix from maui does is to put first all tje directories and from there then so the sorting.

**Comment by milohr** [comment]
Here 
return e1[key] == "inode/directory";

Instesd of the passed key, it needs to be fixed to the Mime key always which is the one that could tells if it is a directory

**Comment by itsvic-dev** [comment]
image

not sure, it works fine - took long to load but it loaded fine

**Comment by itsvic-dev** [comment]
my /bin has 3770 files, which explains the long loading time

**Comment by milohr** [comment]
> my /bin has 3770 files, which explains the long loading time

But it is not sorting the folders first, right?

Try changing back the line 194 back to this?

            return e1[FMH::MODEL_KEY::MIME] == "inode/directory";
 To put folders first and see if it crashes?

**Comment by itsvic-dev** [comment]
> But it is not sorting the folders first, right?

it doesn't sort it immediately, only after it finishes loading in all the files

> Try changing back the line 194 back to this?
> 
> ```
>         return e1[FMH::MODEL_KEY::MIME] == "inode/directory";
> ```
> 
> To put folders first and see if it crashes?

ok, but like... why? the current solution works fine?

**Comment by milohr** [comment]
> > But it is not sorting the folders first, right?
> 
> it doesn't sort it immediately, only after it finishes loading in all the files
> 
> > Try changing back the line 194 back to this?
> > ```
> >         return e1[FMH::MODEL_KEY::MIME] == "inode/directory";
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > To put folders first and see if it crashes?
> 
> ok, but like... why? the current solution works fine?

Hmm thats super weird, from what i can read this pr wouldnt sort folders first.  I will have to test it myself then, to be sure. But on index i tried to replicate this and change qsort to std sort and it crashed, that why i reviewed the code and corrected it. Im compiling this to check

**Comment by itsvic-dev** [comment]
ok, i think i see what you mean, indeed the folders aren't sorted first, they're sorted by filename

**Comment by itsvic-dev** [comment]
image

sometimes it causes File Manager to hang, sometimes it causes File Manager to crash, hmm. very weird

**Comment by milohr** [comment]
> image
> 
> sometimes it causes File Manager to hang, sometimes it causes File Manager to crash, hmm. very weird

The changes i link to fix this and it is actually a wsy more optimal solution. The previois one was bad and ugly 😑

**Comment by milohr** [comment]
Btw i meant to propose to your team to work on a common backend logic base and then it can be used by any wanted ui framework. Since qt and qml make this super easy i thought it would be a good idea, im open to ideas. Let me know what you think about it

**Comment by itsvic-dev** [comment]
your solution does indeed work! thank you!



> Btw i meant to propose to your team to work on a common backend logic base and then it can be used by any wanted ui framework. Since qt and qml make this super easy i thought it would be a good idea, im open to ideas. Let me know what you think about it

i'm not quite sure about it, i'm already busy as is :P

what are your thoughts on it? @rekols

**Comment by milohr** [comment]
> your solution does indeed work! thank you!
> 
> > Btw i meant to propose to your team to work on a common backend logic base and then it can be used by any wanted ui framework. Since qt and qml make this super easy i thought it would be a good idea, im open to ideas. Let me know what you think about it
> 
> i'm not quite sure about it, i'm already busy as is :P
> 
> what are your thoughts on it? @rekols

Mauikit has already been split into sub libraries incljdong FileBrowsing ImageTools TextEditor among others. So you could use FileBrowsing and we can perform the needed fixes that would alllow you to use it as wanted. That way it would increase  shared fixes and so on...

**Pull request merged**
